# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Como te gustar\xeda que se imprima en tu gafete.(si quer\xe9s puede ser un nick)', max_length=100, verbose_name='Nombre completo o nick')),
                ('annotation', models.TextField(blank=True, help_text='Si ten\xe9s alguna necesidad particular que necesites que contemplemos para el evento contanos y haremos lo posible por ayudarte. Te recomendamos reservar tu vianda para los d\xedas s\xe1bado y domingo, ya que cerca del complejo las ofertas gastron\xf3micas son reducidas Podr\xe1s elegir el tipo de vianda de acuerdo a tus necesidades. Encontrar\xe1s el link para hacerlo al confirmar la registraci\xf3n.', null=True, verbose_name='Observaciones')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, upload_to='attendees_cvs', verbose_name='Curriculum vitae')),
                ('show_to_sponsor', models.BooleanField(help_text='Acepto que mis datos personales se compartan con los sponsors', verbose_name='Compartir mis datos personales')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_tacc', models.BooleanField(default=False)),
                ('meal_on_saturday', models.IntegerField(blank=True, null=True)),
                ('meal_on_sunday', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_s', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_m', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_l', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_xl', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_xxl', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_xxxl', models.IntegerField(blank=True, null=True)),
                ('tshirt_male_xxxxl', models.IntegerField(blank=True, null=True)),
                ('tshirt_female_s', models.IntegerField(blank=True, null=True)),
                ('tshirt_female_m', models.IntegerField(blank=True, null=True)),
                ('tshirt_female_l', models.IntegerField(blank=True, null=True)),
                ('tshirt_female_xl', models.IntegerField(blank=True, null=True)),
                ('is_acredited', models.BooleanField(default=False)),
                ('amount_to_pay', models.IntegerField(default=0)),
                ('require_certificate', models.BooleanField(default=False)),
                ('wanna_party', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['full_name'],
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
    ]
