# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_auto_20161113_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_tacc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meal_on_saturday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meal_on_sunday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_female_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_female_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_female_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_female_xl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_xl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_xxl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_xxxl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tshirt_male_xxxxl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
