# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0006_auto_20161123_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_acredited',
            field=models.BooleanField(default=False),
        ),
    ]
