# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_attendee_is_acredited'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='has_to_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='require_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='wanna_party',
            field=models.BooleanField(default=False),
        ),
    ]
