# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0008_auto_20161124_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='has_to_pay',
        ),
        migrations.AddField(
            model_name='attendee',
            name='amount_to_pay',
            field=models.IntegerField(default=0),
        ),
    ]
